# Generated by Django 5.2 on 2025-04-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bacterie',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='bacterie_images/'),
        ),
        migrations.AddField(
            model_name='bacterie',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='bacterie_images/'),
        ),
        migrations.AddField(
            model_name='bacterie',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='bacterie_images/'),
        ),
        migrations.AddField(
            model_name='bacterie',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='bacterie_images/'),
        ),
        migrations.AddField(
            model_name='bacterie',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='bacterie_images/'),
        ),
        migrations.AddField(
            model_name='bacterie',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='bacterie_images/'),
        ),
        migrations.AddField(
            model_name='bacterie',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='bacterie_images/'),
        ),
        migrations.AddField(
            model_name='bacterie',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='bacterie_images/'),
        ),
    ]
