# Generated by Django 5.2 on 2025-06-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bacterie_image1_bacterie_image2_bacterie_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbacterie',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='group_bacterie_images/'),
        ),
    ]
